# Generated by Django 3.1.4 on 2021-01-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='Lorem ipsum dolor si amet, dude just a summary', max_length=30),
            preserve_default=False,
        ),
    ]
